### ISSUE TITLE
Figure out communication between backend and frontend

### ISSUE THREAD

**Issue by memo1918** [Dawinartor/Minesweaper#7]
[This link](https://healeycodes.com/talking-between-languages) shows one of the solutions using fetch()

**Comment by Dawinartor** [comment]
During testing to get JSON from back-end  to use it in front-end was no possibility to access the data in a normal way. Finally @memo1918 was able to access them by getting the object through a second script but its not like a good solution.

The biggest problem was, the game field is shown in page source data.

**Comment by Dawinartor** [comment]
Looking for a more practical solution like sessionStorage or even better with config of GET by Flask to access JSON in  Gamefield.js

**Comment by Dawinartor** [comment]
I figured out a difference between using a JSON from Flask and [using a JSON from Flask in an external JS file](https://stackoverflow.com/questions/65852714/get-json-from-flask-using-an-external-js-file).

**Comment by Dawinartor** [comment]
Instead of using a HTTP method GET we are using a hidden input element in body of Gamefield.html. This element is hidden, so you can not see it in HTML and it contains the gamefield JSON object to communicate between back-end & front-end.

Sadly the source code problem sill happens. 
Just in a other place of HTML.

**Comment by Dawinartor** [comment]
@memo1918 I can not access the values like we planed. 
Could you take my solution please, because this is the more practical way and figure out how to access the values inside?
